name: build

on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use local my-action
        uses: ./.github/actions/mbglc
